### ISSUE TITLE
Add meta data to data export

### ISSUE THREAD

**Issue by joycarpediem** [akvo/wai-ethiopia#83] opened 2021-11-10 06:20 UTC
The filter with which the data was created and the date the file was generated

**Comment by joycarpediem** [comment] 2021-11-10 06:45
Sheet name : Context
Date of file generation
Filter

**Comment by dedenbangkit** [comment] 2021-11-10 09:52
Duplicate of [#75](https://github.com/akvo/wai-ethiopia/issues/75#issuecomment-964826180)

**Comment by dedenbangkit** [comment] 2021-11-11 09:49
IN THE FILE

**Closed** 2021-11-11 17:30 UTC
Labels: Data export
